# Generated by Django 3.2.16 on 2023-09-23 17:34

from django.db import migrations, models
import users.models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230923_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, help_text='Required. 254 characters or fewer.', max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=users.models.CharField(help_text='Required. 150 characters or fewer.', max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=users.models.CharField(help_text='Required. 150 characters or fewer.', max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=users.models.CharField(help_text='Required. 150 characters or fewer.', max_length=150, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=users.models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer.', max_length=150, unique=True, validators=[users.validators.username_validator], verbose_name='username'),
        ),
    ]
