# Generated by Django 3.2.16 on 2023-09-30 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_subscribe_recipes_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscriptions',
            field=models.ManyToManyField(through='users.Subscribe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.CheckConstraint(check=models.Q(('author__exact', django.db.models.expressions.F('follower')), _negated=True), name='check_self_subscribe'),
        ),
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.UniqueConstraint(fields=('author', 'follower'), name='unique_subscribe'),
        ),
    ]
