# Generated by Django 3.2.16 on 2023-09-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230930_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='recipes_limit',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='recipes limit'),
        ),
    ]
