# Generated by Django 3.2.16 on 2023-10-01 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_subscribe_recipes_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='recipes_limit',
        ),
    ]
