# Generated by Django 3.2.16 on 2023-11-06 19:44

from django.db import migrations, models
import django.db.models.expressions
import recipes.models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20231106_2328'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favoritelist',
            name='unique recipe in favorite',
        ),
        migrations.RemoveConstraint(
            model_name='recipeingridient',
            name='unique ingridient in recipe',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique recipe in shopping',
        ),
        migrations.RemoveConstraint(
            model_name='subscribe',
            name='check self subscribe',
        ),
        migrations.RemoveConstraint(
            model_name='subscribe',
            name='unique subscribe',
        ),
        migrations.AlterField(
            model_name='ingridient',
            name='name',
            field=recipes.models.CharField200(default=recipes.validators.default_name, help_text='Required. 200 characters or fewer.', max_length=200, verbose_name='name item'),
        ),
        migrations.AlterField(
            model_name='measurementunit',
            name='name',
            field=recipes.models.CharField200(default=recipes.validators.default_name, help_text='Required. 200 characters or fewer.', max_length=200, verbose_name='name item'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=recipes.models.CharField200(default=recipes.validators.default_name, help_text='Required. 200 characters or fewer.', max_length=200, verbose_name='name item'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=recipes.models.CharField200(default=recipes.validators.default_name, help_text='Required. 200 characters or fewer.', max_length=200, verbose_name='name item'),
        ),
        migrations.AddConstraint(
            model_name='favoritelist',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='дублирование любимого кулинарного рецепта'),
        ),
        migrations.AddConstraint(
            model_name='recipeingridient',
            constraint=models.UniqueConstraint(fields=('ingridient', 'recipe'), name='дублирование ингридиента в кулинарном рецепте'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='дублирование кулинарного рецепта в списке покупок'),
        ),
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.CheckConstraint(check=models.Q(('author__exact', django.db.models.expressions.F('follower')), _negated=True), name='проверка подписки на самого себя'),
        ),
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.UniqueConstraint(fields=('author', 'follower'), name='дублирование подписки'),
        ),
    ]
