# Generated by Django 3.2.16 on 2023-11-06 21:08

from django.db import migrations
import recipes.models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20231106_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridient',
            name='name',
            field=recipes.models.CharField200(default=recipes.validators.default_name, help_text='Required. 200 characters or fewer.', max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='measurementunit',
            name='name',
            field=recipes.models.CharField200(default=recipes.validators.default_name, help_text='Required. 200 characters or fewer.', max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=recipes.models.CharField200(default=recipes.validators.default_name, help_text='Required. 200 characters or fewer.', max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=recipes.models.CharField200(default=recipes.validators.default_name, help_text='Required. 200 characters or fewer.', max_length=200, verbose_name='name'),
        ),
    ]
