# Generated by Django 3.2.16 on 2023-11-06 21:22

from django.db import migrations, models
import recipes.models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20231107_0108'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipeingridient',
            name='дублирование ингридиента в кулинарном рецепте',
        ),
        migrations.AlterField(
            model_name='ingridient',
            name='name',
            field=recipes.models.CharField200(default=recipes.validators.default_name, help_text='Required. 200 characters or fewer.', max_length=200, verbose_name='item name'),
        ),
        migrations.AlterField(
            model_name='measurementunit',
            name='name',
            field=recipes.models.CharField200(default=recipes.validators.default_name, help_text='Required. 200 characters or fewer.', max_length=200, verbose_name='item name'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=recipes.models.CharField200(default=recipes.validators.default_name, help_text='Required. 200 characters or fewer.', max_length=200, verbose_name='item name'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=recipes.models.CharField200(default=recipes.validators.default_name, help_text='Required. 200 characters or fewer.', max_length=200, verbose_name='item name'),
        ),
        migrations.AddConstraint(
            model_name='recipeingridient',
            constraint=models.UniqueConstraint(fields=('ingridient', 'recipe'), name='дублирование ингредиента в кулинарном рецепте'),
        ),
    ]
